language: cpp

compiler: 
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - cd Install-OpenCV/Ubuntu/2.4
  - chmod +x opencv2_4_9.sh
  - ./opencv2_4_9.sh
  - cd ../../..
  
before_script:
  - mkdir bin
  
script: make skin-detect
