language: cpp

compiler: 
  - gcc
  - clang

before_install:
  - chmod +x Install-OpenCV/Ubuntu/opencv_latest.sh
  - ./Install-OpenCV/Ubuntu/opencv_latest.sh
  
before_script:
  - mkdir bin
  
script: make skin-detect
