language: cpp

compiler: 
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcv-dev libopencv-dev libhighgui-dev
  
before_script:
  - mkdir bin
  
script: make skin-detect
